# SITE CONFIGURATION
markdown:         CommonMarkGhPages

baseurl:          /
permalink:        none

future:           true
service_worker:   true

# PLUGINS
plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# jekyll-commonmark-ghpages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

# jekyll-mentions
jekyll-mentions:
  base_url: https://twitter.com

# jekyll-optional-front-matter
include:
  - _pages
  - docs/CONTRIBUTING.md

# jekyll-paginate
paginate:         1
paginate_path:    '/:num'

# jekyll-remote-theme
#remote_theme: esovm/minima
#remote_theme: defustujacaistota/defustujacaistota
#remote_theme: twocolumn/master
remote_theme: twocolumn/WriteOnly

# jekyll-seo-tag
title:            Two Column
tagline:          Two Column
description:      "Two Column"
url:              https://twocolumn.github.io/
author:           kamil-adam
logo:             /assets/img/logo.jpg

social:
  name: Kamil Adam # You :P
  links:
    - https://github.com/twocolumn
    - https://www.linkedin.com/company/writeonly-pl
    - https://www.facebook.com/WriteOnlyPL
    - https://www.instagram.com/degustujacaistota/
    - https://twitter.com/TheKamilAdam
#    - https://plus.google.com/+BenBalter
#    - https://keybase.io/benbalter

# THEME SETTINGS

# Custom vars
version:          0.0.0

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID
# google_analytics: UA-XXXXXXXXX-X

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname


# minima
#show_excerpts: true

header_pages:
  - README.md
#  - docs/INSTALL.md
#  - docs/TODO.md
#  - docs/NEWS.md
#  - docs/BUGS.md
#  - docs/FAQ.md

# SOCIAL LINKS
social_links:
  github:  twocolumn
  linkedin: writeonly-pl
  facebook: WriteOnlyPL
  instagram: degustujacaistota
  twitter: TheKamilAdam
  #  microdotblog: jekyll
  rss: rss
  # dribbble: jekyll
  # flickr:   jekyll
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: CloudCannon
  # telegram: jekyll
  # googleplus: +jekyll
  # keybase: jekyll
