markdown: CommonMarkGhPages

title:            Two Column
tagline:          Two Column
description:      "Two Column"
url:              https://twocolumn.github.io/
author:           kamil-adam

permalink: none
service_worker: true
future: true

plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme          # brilliant
  - jekyll-sass-converter        # https://jekyllrb.com/docs/assets/
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# jekyll-commonmark-ghpages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

# jekyll-mentions
jekyll-mentions:
  base_url: https://twitter.com

# jekyll-optional-front-matter
include:
  - _pages
  - docs/CONTRIBUTING.md

# jekyll-paginate
paginate:         1
paginate_path:    '/:num'

# jekyll-remote-theme
#remote_theme: esovm/minima
#remote_theme: defustujacaistota/defustujacaistota
remote_theme: twocolumn/master
#remote_theme: twocolumn/WriteOnly


# minima
show_excerpts: true
# skin: sunrise

header_pages:
  - README.md
#  - docs/INSTALL.md
#  - docs/TODO.md
#  - docs/NEWS.md
#  - docs/BUGS.md
#  - docs/FAQ.md

minima:
#  date_format: "%b %-d, %Y"
  social_links:
    rss: rss
    github: twocolumn
#    twitter: jekyllrb
#    dribbble: jekyll
#    facebook: jekyll
#    flickr: jekyll
#    instagram: jekyll
#    linkedin: jekyll
#    pinterest: jekyll
#    telegram: jekyll
#    googleplus: +jekyll
#    microdotblog: jekyll
#    keybase: jekyl
